# Explicit index of every repository NixOS module.
# Explicitly import every repository NixOS module.
# Keep this list alphabetical so adding a module is straightforward.
{ ... }:

{
  imports = [
    ./apps/blender
    ./apps/bottles
    ./apps/bs-manager
    ./apps/calibre
    ./apps/chrome
    ./apps/darktable
    ./apps/discord
    ./apps/dolphin
    ./apps/eden
    ./apps/element
    ./apps/evolution
    ./apps/firefox
    ./apps/gamemode
    ./apps/godot
    ./apps/heroic-launcher
    ./apps/jellyfin
    ./apps/keymapp
    ./apps/kodi
    ./apps/lutris
    ./apps/mangohud
    ./apps/microsoft-edge
    ./apps/nexusmods-app
    ./apps/orca
    ./apps/oversteer
    ./apps/pcsx2
    ./apps/pixelorama
    ./apps/prismlauncher
    ./apps/proton-pass
    ./apps/proton-vpn
    ./apps/protontricks
    ./apps/r2modman
    ./apps/rpcs3
    ./apps/ryujinx
    ./apps/sidequest
    ./apps/slack
    ./apps/spotify
    ./apps/star-citizen
    ./apps/steam
    ./apps/steamtinkerlaunch
    ./apps/texlive
    ./apps/tidal
    ./apps/ultrastar
    ./apps/unigine
    ./apps/vlc
    ./apps/vscode
    ./apps/winetricks
    ./apps/xournalpp
    ./cli-apps/android-platform-tools
    ./cli-apps/conda
    ./cli-apps/ffbtools
    ./cli-apps/fusee-nano
    ./cli-apps/julia
    ./cli-apps/liquidctl
    ./cli-apps/mprime
    ./cli-apps/nixd
    ./cli-apps/proton
    ./cli-apps/wine
    ./desktop/addons/electron-support
    ./desktop/addons/wallpaper
    ./desktop/addons/xdg-portal
    ./desktop/gnome
    ./desktop/kodi
    ./hardware/audio
    ./hardware/fingerprint
    ./hardware/networking
    ./hardware/storage
    ./hardware/surface
    ./hardware/tablet
    ./home
    ./nix
    ./security/gpg
    ./security/keyring
    ./security/pass
    ./services/adguard
    ./services/authelia
    ./services/avahi
    ./services/calibre-web
    ./services/flatpak
    ./services/jellyfin
    ./services/jellyseerr
    ./services/openssh
    ./services/redis
    ./services/samba
    ./services/sshServe
    ./services/traefik
    ./services/virtualisation
    ./services/zfs
    ./profiles/benchmarking
    ./profiles/browsers
    ./profiles/common
    ./profiles/compchem
    ./profiles/creative
    ./profiles/desktop
    ./profiles/development
    ./profiles/emulation
    ./profiles/gamedev
    ./profiles/gaming
    ./profiles/htpc
    ./profiles/media
    ./profiles/nas
    ./profiles/social
    ./profiles/tuning
    ./profiles/vr
    ./system/boot
    ./system/env
    ./system/fonts
    ./system/kb
    ./system/locale
    ./system/time
    ./tools/appimage
    ./tools/diagnostics
    ./tools/direnv
    ./tools/git
    ./tools/misc
    ./tools/rpi
    ./tools/sensors
    ./tools/usb-modeswitch
    ./user
  ];
}
